services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    devices:
      - nvidia.com/gpu=all

  ollama-run:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    entrypoint: >
      sh -c "until curl -s http://ollama:11434/health >/dev/null 2>&1; do echo 'waiting for ollama...'; sleep 1; done;
             echo 'running ollama run...';
             ollama run qwen3.5:0.8b 'Hello, world' --hidethinking;
             echo 'done.'"
    restart: "no"