# Generated by Django 6.0.5 on 2026-05-31 23:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todoitem_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('thread_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
