# Generated by Django 6.0.5 on 2026-06-04 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='thread_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
